### ISSUE TITLE
openssh design model

### ISSUE THREAD

**Issue by mudongliang** [fgimian/multi-ssh#1]
I have a question about openssh design model!
You created multi-ssh here. Are you sure that openssh is single process(multithread)?
And why do you want to change single process to multiple processes? For security, performance, or other reasons?

**Comment by fgimian** [comment]
Hi, this multiprocessing is performed on the server which is making multiple SSH connections to the clients.  This is the same technique used by popular libraries like Ansible and Fabric.

This is done purely for performance reasons.

Cheers
Fotis

**Comment by mudongliang** [comment]
![privs](https://cloud.githubusercontent.com/assets/6214861/12581371/225d7886-c471-11e5-97f1-e797a4aa5f3d.jpg)

**Comment by mudongliang** [comment]
I don't understand much about "make multiple SSH connections to the clients". Can you teach me your idea about multi-ssh in the above picture?

**Comment by fgimian** [comment]
Your diagram only shows a single connection, and that is what is being done in parallel across many servers.  The parallelism is required to connect to multiple servers at a time and for each server to run a particular command simultaneously to speed up processing.

I suggest that this library simply may not be what you're looking for if it's not making sense.  Please check out the [Fabric Python library](http://www.fabfile.org/) to gain a better understanding of what's being done here.

I'll close this issue now.

Cheers
Fotis
